services:
  microservice1:
    build:
      context: ./services/microservice1
    ports:
      - "8000:8000"
    container_name: microservice1
  
  config_service:
    build:
      context: ./services/config_service
    ports:
      - "8001:8001"
    container_name: config_service
