version: 1
formatters:
  logging:
    format: '[%(asctime)s] | %(levelname)s | %(processName)s:%(threadName)s:%(thread)s | [%(module)s::%(funcName)s:%(lineno)d] | %(message)s'
  colorlog:
    (): 'colorlog.ColoredFormatter'
    format: '%(log_color)s[%(asctime)s] | %(levelname)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: logging
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: logging
    filename: ./log/servant.log
    when: midnight
    encoding: utf8
  colour:
    class: logging.StreamHandler
    level: INFO
    formatter: colorlog
loggers:
  '':
    level: INFO
    handlers: [ colour, file ]
    propagate: yes
