name: Pylint

on:
  push

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          # Main application
          PYTHONPATH=. pylint --persistent=n $(git ls-files '*.py' \
              ':!:services/config_service/**' \
              ':!:services/microservice1/**')
      
          # Config service
          PYTHONPATH=services/config_service \
              pylint --persistent=n services/config_service/app
      
          # Microservice 1
          PYTHONPATH=services/microservice1 \
              pylint --persistent=n services/microservice1/app
